# JWT微服务认证配置示例 (SpringBoot 3.0+)
# 将此配置添加到微服务的 application.yml 中

# Sa-Token 配置
sa-token:
  # token 名称
  token-name: satoken
  # token 有效期（秒）
  timeout: 2592000
  # token 活跃有效期（秒）
  activity-timeout: 1800
  # 是否允许并发登录
  is-concurrent: true
  # 是否共享token
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出日志
  is-log: true
  # 是否从header中读取token
  is-read-header: true
  # token前缀
  token-prefix: Bearer

# Synapse JWT 配置
synapse:
  jwt:
    # 启用JWT认证
    enabled: true
    # JWT密钥（生产环境请使用更复杂的密钥）
    secret: "your-super-secret-jwt-signing-key-here"
    # JWT过期时间（秒）
    expiration: 1800
    # 是否在日志中输出调试信息
    debug: false

# Redis 配置（用于存储用户会话）
spring:
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# 日志配置
logging:
  level:
    com.indigo.security: DEBUG
    cn.dev33.satoken: INFO
    root: INFO

# 微服务间调用配置示例
feign:
  client:
    config:
      default:
        # 连接超时时间
        connectTimeout: 5000
        # 读取超时时间
        readTimeout: 5000
        # 日志级别
        loggerLevel: basic
        # 请求拦截器（可用于自动添加JWT token）
        requestInterceptors:
          - com.indigo.security.interceptor.JWTFeignInterceptor 