package com.indigo.core.constants;

import lombok.Getter;

/**
 * 标准错误码枚举
 * 提供框架内置的标准错误码
 * 
 * @author 史偕成
 * @date 2025/03/21
 */
@Getter
public enum StandardErrorCode implements ErrorCode {
    // 系统级错误码
    BASE_SUCCESS("200"),
    BASE_ERROR("SYS000"),
    ILLEGAL_STATE("SYS011"),
    SYSTEM_ERROR("SYS001"),
    PARAM_ERROR("SYS002"),
    UNAUTHORIZED("SYS003"),
    FORBIDDEN("SYS004"),
    NOT_FOUND("SYS005"),
    METHOD_NOT_ALLOWED("SYS006"),
    REQUEST_TIMEOUT("SYS007"),
    TOO_MANY_REQUESTS("SYS008"),
    RATE_LIMIT_EXCEEDED("SYS012"),
    SERVICE_UNAVAILABLE("SYS009"),
    GATEWAY_ERROR("SYS010"),
    THREAD_ERROR("SYS013"),

    // 业务级错误码
    BUSINESS_ERROR("BUS001"),
    DATA_NOT_FOUND("BUS002"),
    DATA_ALREADY_EXISTS("BUS003"),
    DATA_INVALID("BUS004"),
    OPERATION_FAILED("BUS005"),
    OPERATION_TIMEOUT("BUS006"),
    OPERATION_FORBIDDEN("BUS007"),
    OPERATION_NOT_ALLOWED("BUS008"),
    OPERATION_INVALID("BUS009"),
    OPERATION_CONFLICT("BUS010"),

    // 安全认证相关错误码
    SECURITY_ERROR("SEC001"),
    NOT_LOGIN("SEC002"),
    LOGIN_FAILED("SEC003"),
    LOGIN_EXPIRED("SEC004"),
    TOKEN_INVALID("SEC005"),
    TOKEN_EXPIRED("SEC006"),
    TOKEN_MISSING("SEC007"),
    PERMISSION_DENIED("SEC008"),
    ROLE_DENIED("SEC009"),
    ACCOUNT_DISABLED("SEC010"),
    ACCOUNT_LOCKED("SEC011"),
    MFA_REQUIRED("SEC012"),
    MFA_FAILED("SEC013"),
    SESSION_INVALID("SEC014"),
    SESSION_EXPIRED("SEC015"),
    OAUTH_ERROR("SEC016"),
    OAUTH_INVALID_CLIENT("SEC017"),
    OAUTH_INVALID_GRANT("SEC018"),
    OAUTH_ACCESS_DENIED("SEC019"),

    // IAM相关错误码
    IAM_ERROR("IAM001"),
    USER_NOT_FOUND("IAM002"),
    USER_ALREADY_EXISTS("IAM003"),
    USER_INVALID("IAM004"),
    USER_DISABLED("IAM005"),
    USER_LOCKED("IAM006"),
    USER_EXPIRED("IAM007"),
    USER_CREDENTIALS_INVALID("IAM008"),
    USER_CREDENTIALS_EXPIRED("IAM009"),
    USER_CREDENTIALS_LOCKED("IAM010"),

    // 工作流相关错误码
    WORKFLOW_ERROR("WF001"),
    WORKFLOW_NOT_FOUND("WF002"),
    WORKFLOW_ALREADY_EXISTS("WF003"),
    WORKFLOW_INVALID("WF004"),
    WORKFLOW_DISABLED("WF005"),
    WORKFLOW_LOCKED("WF006"),
    WORKFLOW_EXPIRED("WF007"),
    WORKFLOW_INSTANCE_NOT_FOUND("WF008"),
    WORKFLOW_INSTANCE_INVALID("WF009"),
    WORKFLOW_INSTANCE_COMPLETED("WF010"),

    // 审计相关错误码
    AUDIT_ERROR("AUD001"),
    AUDIT_NOT_FOUND("AUD002"),
    AUDIT_ALREADY_EXISTS("AUD003"),
    AUDIT_INVALID("AUD004"),
    AUDIT_DISABLED("AUD005"),
    AUDIT_LOCKED("AUD006"),
    AUDIT_EXPIRED("AUD007"),
    AUDIT_OPERATION_NOT_ALLOWED("AUD008"),
    AUDIT_OPERATION_INVALID("AUD009"),
    AUDIT_OPERATION_CONFLICT("AUD010");

    private final String code;

    StandardErrorCode(String code) {
        this.code = code;
    }
}
