# Synapse Framework 数据源配置示例
# 复制此文件到您的项目中，并根据实际环境修改配置

synapse:
  datasource:
    # 主数据源名称
    primary: master
    
    # 读写分离配置
    read-write:
      enabled: true
      read-sources: [slave1, slave2]
      write-sources: [master]
    
    # 负载均衡配置
    load-balance:
      strategy: ROUND_ROBIN
      weights:
        slave1: 100
        slave2: 80
    
    # 故障转移配置
    failover:
      enabled: true
      timeout: 5000
      max-retries: 3
      strategy: PRIMARY_FIRST
    
    # 数据源配置
    datasources:
      master:
        type: MYSQL
        host: localhost
        port: 3306
        database: synapse_demo
        username: root
        password: 123456
        role: WRITE
        
        pool:
          type: HIKARI
          min-idle: 5
          max-size: 20
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
          connection-test-query: SELECT 1
          leak-detection-threshold: 60000
          
      slave1:
        type: MYSQL
        host: localhost
        port: 3307
        database: synapse_demo
        username: root
        password: 123456
        role: READ
        
        pool:
          type: HIKARI
          min-idle: 5
          max-size: 15
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
          connection-test-query: SELECT 1
          
      slave2:
        type: MYSQL
        host: localhost
        port: 3308
        database: synapse_demo
        username: root
        password: 123456
        role: READ
        
        pool:
          type: HIKARI
          min-idle: 5
          max-size: 15
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
          connection-test-query: SELECT 1

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.**.entity
  mapper-locations: classpath*:mapper/**/*.xml

# 健康检查端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always

# 日志配置
logging:
  level:
    com.indigo.databases: DEBUG
    org.springframework.jdbc: DEBUG
