# Synapse Framework 数据库模块配置示例
# 支持两种配置方式：synapse.datasource 和 spring.datasource.dynamic

# 方式1: 使用 synapse.datasource 配置（推荐）
synapse:
  datasource:
    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
        cache-enabled: true
        lazy-loading-enabled: true
        aggressive-lazy-loading: false
        multiple-result-sets-enabled: true
        use-column-label: true
        use-generated-keys: false
        auto-mapping-behavior: PARTIAL
        auto-mapping-unknown-column-behavior: WARNING
        default-executor-type: SIMPLE
        default-statement-timeout: 25
        default-fetch-size: 100
        safe-row-bounds-enabled: false
        safe-result-handler-enabled: true
        local-cache-scope: SESSION
        lazy-load-trigger-methods: "equals,clone,hashCode,toString"
      global-config:
        banner: false
        enable-sql-runner: false
        enable-meta-object-handler: true
        enable-sql-injector: true
        enable-pagination: true
        enable-optimistic-locker: true
        enable-block-attack: true
      type-aliases-package: com.indigo.**.entity
      mapper-locations: "classpath*:mapper/**/*.xml"
    primary: master1
    dynamic-data-source:
      strict: false
      seata: false
      p6spy: false
      datasource:
        master1:
          type: MYSQL
          host: localhost
          port: 3306
          database: synapse_iam
          username: root
          password: mamnan920130.
          pool-type: HIKARI
          params:
            useUnicode: "true"
            characterEncoding: "utf8"
            useSSL: "false"
            serverTimezone: "Asia/Shanghai"
          hikari:
            minimum-idle: 5
            maximum-pool-size: 15
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: "SELECT 1"
            connection-init-sql: ""
            validation-timeout: 5000
            leak-detection-threshold: 0
            register-mbeans: false
        slave1:
          type: MYSQL
          host: localhost
          port: 3306
          database: synapse_iam_slave
          username: root
          password: mamnan920130.
          pool-type: HIKARI
          params:
            useUnicode: "true"
            characterEncoding: "utf8"
            useSSL: "false"
            serverTimezone: "Asia/Shanghai"
          hikari:
            minimum-idle: 3
            maximum-pool-size: 10
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: "SELECT 1"

# 方式2: 使用标准Spring Boot配置（兼容性）
spring:
  datasource:
    dynamic:
      primary: master1
      strict: false
      datasource:
        master1:
          type: MYSQL
          host: localhost
          port: 3306
          database: synapse_iam
          username: root
          password: mamnan920130.
          pool-type: HIKARI
          params:
            useUnicode: "true"
            characterEncoding: "utf8"
            useSSL: "false"
            serverTimezone: "Asia/Shanghai"
          hikari:
            minimum-idle: 5
            maximum-pool-size: 15
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: "SELECT 1"

# MyBatis-Plus 标准配置（可选）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: PARTIAL
    auto-mapping-unknown-column-behavior: WARNING
    default-executor-type: SIMPLE
    default-statement-timeout: 25
    default-fetch-size: 100
    safe-row-bounds-enabled: false
    safe-result-handler-enabled: true
    local-cache-scope: SESSION
    lazy-load-trigger-methods: "equals,clone,hashCode,toString"
  global-config:
    banner: false
    enable-sql-runner: false
    enable-meta-object-handler: true
    enable-sql-injector: true
    enable-pagination: true
    enable-optimistic-locker: true
    enable-block-attack: true
  type-aliases-package: com.indigo.**.entity
  mapper-locations: "classpath*:mapper/**/*.xml" 